w4/w4d5/musicapp/config/routes.rb
Musicapp::Application.routes.draw do
  root to: "users#new"
  
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  
  resources :bands do
    resources :albums, only: [:create, :index, :new]
  end
    
  resources :albums, only: [:edit, :destroy, :show, :update] do
    resources :tracks, only: [:create, :index, :new]
  end
  resources :tracks, only: [:show] do
    resources :notes, only: [:create, :new, :destroy]
  end
    
  resources :tracks, only: [:edit, :destroy, :update]
  post '/user/:id/activate', to: 'users#active', as: 'activate'

end

w4/w4d5/musicapp/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  track_id   :integer          not null
#  body       :text             not null
#  created_at :datetime
#  updated_at :datetime
#

class Note < ActiveRecord::Base
  validates :user_id, :track_id, :body, presence: true
  
  belongs_to  :user,
              class_name: 'User',
              foreign_key: :user_id,
              primary_key: :id
              
  belongs_to  :track,
              class_name: 'Track',
              foreign_key: :track_id,
              primary_key: :id              
              
end

w4/w4d5/musicapp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :view_if_logged_in
  
  def new
    @note = Note.new
    render :new
  end
  
  def create
    @note = Note.new(note_params)
    @note.track_id = params[:track_id]
    @note.user_id = current_user.id
    
    if @note.save
      redirect_to track_url(@note.track_id)
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to track_url(@note.track_id)
    end
  end
  
  def destroy
    @note = Note.find_by_id(params[:id])
    track_id = @note.track_id
    @note.delete
    redirect_to track_url(track_id)
  end
  
  private
  
  def note_params
    params.require(:note).permit(:body)
  end
  
end

w4/w4d5/musicapp/app/helpers/notes_helper.rb
module NotesHelper
end

w4/w4d5/musicapp/app/views/notes/_form.html.erb
<form action="<%= track_notes_url(params[:id]) %>" method="POST">
  
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
  
  <div class='form-group'>
    <label for="body">Note</label>
    <textarea class="form-control" rows="3" name="note[body]" id="body"></textarea>
  </div>
  
  <input type="submit" value="Add Note" class="btn btn-primary">
</form>

w4/w4d5/musicapp/app/views/notes/_note.html.erb
<ul class="list-group">
  <% @track.notes.each do |note| %>
  <li class="list-group-item">
    <blockquote>
      <p><%= note.body%></p>
      <footer>by <%= note.user.email %></footer>    
    </blockquote>   
    <%= button_to 'delete', track_note_url(note.track_id, note.id), method: :delete %>
  </li>
  <% end %>
</ul>