w3/w3d7/blogger/config/routes.rb
Blogger::Application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :tags
  
  root to: 'articles#index'
end

w3/w3d7/blogger/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments,
            class_name: 'Comment',
            foreign_key: :article_id,
            primary_key: :id
            
  has_many :taggings,
            class_name: 'Tagging',
            foreign_key: :article_id,
            primary_key: :id
            
  has_many :tags, through: :taggings, source: :tag
  
  def tag_list
    self.tags.join(", ")
    # self.tags.collect { |tag| tag.name }.join(", ")
  end
  
  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{ |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
                        
end

w3/w3d7/blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article,
              class_name: 'Article',
              foreign_key: :article_id,
              primary_key: :id
end

w3/w3d7/blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
  
  has_many :taggings,
            class_name: 'Tagging',
            foreign_key: :tag_id,
            primary_key: :id  
            
  has_many :articles, through: :taggings, source: :article  
  
  def to_s
    name
  end
            
end

w3/w3d7/blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

w3/w3d7/blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
    
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.create!(article_params)
    
    flash.notice = "Article '#{@article.title}' Created!"
    redirect_to article_path(@article)                  
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.delete
    
    flash.notice = "Article '#{@article.title}' Deleted! "
    
    redirect_to articles_path
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    
    flash.notice = "Article '#{@article.title}' Updated! "
    
    redirect_to article_path(@article)    
  end
  
end

w3/w3d7/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    
    @comment.save
    
    redirect_to article_path(@comment.article)
  end
  
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
  
end

w3/w3d7/blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    @tags = Tag.all
  end
  
  def show
    @tag = Tag.find(params[:id])
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    
    redirect_to tags_path
  end
  
end

w3/w3d7/blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
  
end

w3/w3d7/blogger/app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <p class="comment"><%= comment.body %></p>
</div>

w3/w3d7/blogger/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

w3/w3d7/blogger/app/views/articles/edit.html.erb
<h1>Edit this Article</h1>

<%= render 'articles/form' %>

w3/w3d7/blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %> 
</ul>

w3/w3d7/blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render 'articles/form' %>

w3/w3d7/blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><%= @article.body %></p>
<%= link_to "edit", edit_article_path(@article) %>
<br>
<%= link_to "delete", article_path(@article), method: :delete, data: { confirm: "Really delete the article?"} %>
<%= link_to "<< Back to Articles List", articles_path %>

<br>

<h3>Comments(<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>