w4/w4d5/musicapp/config/routes.rb
Musicapp::Application.routes.draw do
  root to: "users#new"
  
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]
  
  resources :bands do
    resources :albums, only: [:create, :index, :new]
  end
    
  resources :albums, only: [:edit, :destroy, :show, :update] do
    resources :tracks, only: [:create, :index, :new]
  end
  resources :tracks, only: [:show] do
    resources :notes, only: [:create, :new, :destroy]
  end
    
  resources :tracks, only: [:edit, :destroy, :update]
  post '/user/:id/activate', to: 'users#active', as: 'activate'

end

w4/w4d5/musicapp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  bonus      :string(255)      not null
#  lyrics     :text             not null
#  title      :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Track < ActiveRecord::Base  
  BONUS = ["bonus", "regular"]
  
  validates :album_id, :bonus, :lyrics, :title, presence: true
  validates :bonus, inclusion: { in: BONUS }
  
  belongs_to  :album,
              class_name: 'Album',
              foreign_key: :album_id,
              primary_key: :id
              
  has_many    :notes,
              class_name: 'Note',
              foreign_key: :track_id,
              primary_key: :id              

  has_one    :band, through: :album, source: :band
          
end

w4/w4d5/musicapp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  
  before_action :view_if_logged_in
  
  def create
    @track = Track.new(track_params)
    @track.album_id = params[:album_id]
    
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end
  
  def destroy
    @track = Track.find_by_id(params[:id])
    @track.delete
    redirect_to :new
  end
  
  def edit
    @track = Track.find_by_id(params[:id])
    render :edit
  end
  
  def index
    @tracks = Track.all
    render :index
  end
  
  def new
    @track = Track.new
    render :new
  end
  
  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end
  
  def update
    @track = Track.find_by_id(params[:id])
    
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end
  
  private
  
  def track_params
    params.require(:track).permit(:bonus, :lyrics, :title)
  end
  
end

w4/w4d5/musicapp/app/helpers/tracks_helper.rb
module TracksHelper
  
  def get_all_albums
    Album.all    
  end
  
end

w4/w4d5/musicapp/app/views/tracks/_form.html.erb
<% title = (method == :new ? "Add New Track" : "Edit Track Info")  %>
<% action = (method == :new ? album_tracks_url : track_url(params[:id])) %>
<% form_method = (method == :new ? "POST" : "PATCH") %>
<% button_value = (method == :new ? "Add Track" : "Update Track") %>


<h1><%= title %></h1>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <div class='form-group'>
  	<label for='title'>Title: </label><br>
  	<input type='text' name='track[title]' id='title' value="<%= @track.title %>">
  </div>
  
  <div class="form-group">
    <strong>Track Bonus?</strong><br>
    <% ["bonus", "regular"].each do |bonus| %>
    <label for="bonus_<%= bonus %>">
      <input type="radio" name="track[bonus]" id="bonus_<%= bonus %>" value="<%= bonus %>"> <%= bonus.capitalize %>
    </label><br>
    <% end %>
    
  </div>
  
  <div class='form-group'>
  	<label for='lyris'>Lyrics: </label><br>
  	<textarea class="form-control" rows="8" name='track[lyrics]' id='lyrics' value="<%= @track.lyrics %>"></textarea>
  </div>
  
  <input type="submit" value="<%= button_value %>" class='btn btn-primary'>
  
</form>

w4/w4d5/musicapp/app/views/tracks/edit.html.erb
<%= render partial: 'tracks/form', locals: { method: :edit } %>

w4/w4d5/musicapp/app/views/tracks/index.html.erb
<h1>All Tracks - Track's Index Page</h1>
<br>
<table class='table table-stripped table-hover'>
  <thead>
    <tr>
      <th>Track Name</th>
      <th>Edit Track</th>
    </tr>
  </thead>
  <tbody>
  <% @tracks.each do |track| %>
  <tr>
    <td><%= link_to track.title, track_url(track) %></td>
    <td><%= link_to 'edit', edit_track_url(track), class: 'btn btn-success' %></td>
  <tr>
  <% end %>
</ul>

<%= link_to 'Create New Track', new_album_track_url(params[:album_id]) %>

w4/w4d5/musicapp/app/views/tracks/new.html.erb
<%= render partial: 'tracks/form', locals: { method: :new } %>

w4/w4d5/musicapp/app/views/tracks/show.html.erb
<h1>Track's show page for <%= @track.title %></h1>
<br>

<%= link_to 'See Band', band_url(@track.band) %><br>
<%= link_to 'See Album', album_url(@track.album) %><br>

<table class='table table-stripped table-hover'>
  <thead>
    <tr>
      <th>Album Name</th>
      <th>Bonus?</th>
      <th>Lyrics</th>
      <th>Edit Track</th>
      <th>Delete Track</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @track.title %></td>
      <td><%= @track.bonus %></td>
      <td><%= @track.lyrics %></td>    
      <td><%= link_to 'edit', edit_track_url(@track), class: 'btn btn-success' %></td>
      <td><%= link_to 'delete', track_url(@track), method: :delete, class: 'btn btn-success' %></td>
    <tr>
  </tbody>
</table>

<div>
<%= render partial: 'notes/note' %>
<%= render partial: 'notes/form' %>
</div>