w4/w4d3/rentcats/config/routes.rb
Rentcats::Application.routes.draw do
  root to: 'cats#index'

  resources :cats do
    resources :cat_rental_requests, only: [:create, :update]
  end

  post '/cats/:cat_id/cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve', as: 'approve'
  post '/cats/:cat_id/cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny', as: 'deny'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

end

w4/w4d3/rentcats/app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <%= link_to 'Home', root_url %>
    </div>
    <div class="text-right col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <p>
        Created by AppApacademy Jan Cohort 2014 
        <%= link_to '© 99Cats, 2014.', class: 'orange' %>
      </p>
    </div>
  </div>
</footer>

w4/w4d3/rentcats/app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">99Cats</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">View All Cats</a></li>
        <li><a href="<%= new_cat_url %>">Add New Cat</a></li>
      </ul>
    </div>
  </div>
</div>

w4/w4d3/rentcats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render partial: 'layouts/head' %>
<body style="padding-top:50px;">
  <%= render partial: 'layouts/navbar' %>
  <div class = "container">

    <%= render partial: 'layouts/errors' %>

    <% if signed_in? %>
    <ul>
      <li>Signed in as: <%= current_user.user_name %></li>
      <li><%= button_to "Sign Out", session_url, :method => :delete %></li>
    </ul>
    <% else %>
    <%= link_to "Sign In", new_session_url %> or
    <%= link_to "Sign up", new_user_url %>
    <% end %>


    <%= yield %>

  </div>
</body>
</html>